dbt_wallop:
  target: dev
  outputs:
    dev:
      dataset: dev
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: dbt-wallop-dev-1-24a4ba3f890f.json
      location: US
      method: service-account
      priority: interactive
      project: dbt-wallop-dev-1
      threads: 4
      type: bigquery

    prod:
      dataset: prod
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /secrets/dbt-service-keyfile
      location: US
      method: service-account
      priority: interactive
      project: dbt-wallop-prod-1
      threads: 4
      type: bigquery
